# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_gymnastics/',
                'doc_host': 'https://callmephilip.github.io',
                'git_url': 'https://github.com/callmephilip/nbdev-gymnastics/',
                'lib_path': 'nbdev_gymnastics'},
  'syms': { 'nbdev_gymnastics.app': {'nbdev_gymnastics.app.foo': ('app.html#foo', 'nbdev_gymnastics/app.py')},
            'nbdev_gymnastics.check': { 'nbdev_gymnastics.check.AggressiveReporter': ( 'check.html#aggressivereporter',
                                                                                       'nbdev_gymnastics/check.py'),
                                        'nbdev_gymnastics.check.AggressiveReporter.flake': ( 'check.html#aggressivereporter.flake',
                                                                                             'nbdev_gymnastics/check.py'),
                                        'nbdev_gymnastics.check.AggressiveReporter.syntaxError': ( 'check.html#aggressivereporter.syntaxerror',
                                                                                                   'nbdev_gymnastics/check.py'),
                                        'nbdev_gymnastics.check.AggressiveReporter.unexpectedError': ( 'check.html#aggressivereporter.unexpectederror',
                                                                                                       'nbdev_gymnastics/check.py'),
                                        'nbdev_gymnastics.check.check': ('check.html#check', 'nbdev_gymnastics/check.py')},
            'nbdev_gymnastics.foo': { 'nbdev_gymnastics.foo.bar': ('foo.html#bar', 'nbdev_gymnastics/foo.py'),
                                      'nbdev_gymnastics.foo.foo': ('foo.html#foo', 'nbdev_gymnastics/foo.py')}}}
