# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/check.ipynb.

# %% auto 0
__all__ = ['AggressiveReporter', 'check']

# %% ../nbs/check.ipynb 1
import pyflakes.api, nbdev.config

class AggressiveReporter:
    def unexpectedError(self, filename, msg): raise Exception(f"({filename}) Unexpected error: {msg}")
    def syntaxError(self, filename, msg, lineno, offset, text): raise Exception(f"({filename}:{lineno}:{offset}) Syntax error: {msg} {text}")
    def flake(self, message): raise Exception(f"{message}")

def check(): pyflakes.api.checkRecursive([nbdev.config.get_config().lib_path], AggressiveReporter())    
