# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/foo.ipynb.

# %% auto 0
__all__ = ['bar', 'foo']

# %% ../nbs/foo.ipynb 1
def bar():
    return "bar"

# %% ../nbs/foo.ipynb 2
def foo():
    return bar()
